"""create quiz tables

Revision ID: 8553dfd2f555
Revises: 8d5a35927e58
Create Date: 2026-03-15 16:17:39.879746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8553dfd2f555'
down_revision = '8d5a35927e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('time_limit_sec IS NULL OR time_limit_sec > 0', name='ck_quizzes_time_limit_sec_positive'),
    sa.CheckConstraint('total_marks >= 0', name='ck_quizzes_total_marks_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_sec', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.CheckConstraint('score IS NULL OR score <= total_marks', name='ck_quiz_attempts_score_lte_total_marks'),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='ck_quiz_attempts_score_non_negative'),
    sa.CheckConstraint('time_spent_sec IS NULL OR time_spent_sec >= 0', name='ck_quiz_attempts_time_spent_sec_non_negative'),
    sa.CheckConstraint('total_marks >= 0', name='ck_quiz_attempts_total_marks_non_negative'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('correct_json', sa.JSON(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.CheckConstraint('marks >= 0', name='ck_quiz_questions_marks_non_negative'),
    sa.CheckConstraint('question_index >= 0', name='ck_quiz_questions_question_index_non_negative'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'question_index', name='uq_quiz_questions_quiz_question_index')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('quiz_attempt_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('chosen_json', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.CheckConstraint('marks_awarded IS NULL OR marks_awarded >= 0', name='ck_quiz_attempt_answers_marks_awarded_non_negative'),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_quiz_attempt_answers_attempt_question')
    )
    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempt_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_answers_question_id'), ['question_id'], unique=False)

    op.create_table('quiz_question_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'chunk_id', name='uq_quiz_question_sources_question_chunk')
    )
    with op.batch_alter_table('quiz_question_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_question_sources_question_id'), ['question_id'], unique=False)

    # ix_chunks_embedding is intentionally preserved.
    # Alembic cannot reliably diff the pgvector ivfflat index and reports
    # it as removed even when no schema change was made to chunks.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_sources_question_id'))

    op.drop_table('quiz_question_sources')
    with op.batch_alter_table('quiz_attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_answers_attempt_id'))

    op.drop_table('quiz_attempt_answers')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_user_id'))

    op.drop_table('quizzes')
    # ### end Alembic commands ###
